POST https://simple-api-node-qp2m.onrender.com/create
Content-Type: application/json

{
    "title": "Javascript or TypeScript?",
    "description": "What is the difference between his?",
    "duration": 2400
}

###

GET https://simple-api-node-qp2m.onrender.com/videos

###

PUT https://simple-api-node-qp2m.onrender.com/video/2fb5da99-5bb9-4cc5-a409-be2fb9f5a5c4
Content-Type: application/json

{
    "title": "What my opinion about PHP?",
    "description": "In this video i expressed all my opinion about PHP",
    "duration": 5000
}

###

DELETE https://simple-api-node-qp2m.onrender.com/delete/video/8bbfc004-acb2-438b-ab3a-773a9bb8837b